<?php
/*
Plugin Name: PricerrTheme Beyonic
Plugin URI: https://github.com/Ajohnie/pricerrtheme_beyonic
Description: Adds beyonic as a payment gateway to the Pricerr Theme. It facilitates paying through mobile money
Author: Akankwatsa Johnson
Author URI: mailto:jakankwasa.tech@yahoo.com
Version: 1.0
Text Domain: beyonic_gateways
*/


add_filter('PricerrTheme_payment_methods_tabs', 'PricerrTheme_add_new_beyonic_tab');
add_filter('PricerrTheme_payment_methods_action', 'PricerrTheme_add_new_beyonic_pst');
add_filter('PricerrTheme_payment_methods_content_divs', 'PricerrTheme_add_new_beyonic_cnt');
add_filter('pricerrtheme_hook_on_payment_service', 'pricerrtheme_hook_on_payment_service_beyonic');
add_filter('template_redirect', 'beyonic_pricerr_temp_redir');


function beyonic_pricerr_temp_redir()
{

    if (!empty($_GET['beyonic_response_pay_for_job'])) { // response from beyonic through webhook api
        include 'lib/Beyonic.php'; // import beyonic php lib
        $api_key = get_option('PricerrTheme_beyonic_api_key');//api key set in admin tab of beyonic
        $statusrequestAPI = 'https://app.beyonic.com/api/transactions';// use this to query for payment status
        //TODO UPDATE YOUR DB TABLE WITH NEW STATUS FOR TRANSACTION WITH INFO FROM BEYONIC
        wp_redirect(get_site_url()); // redirect to any appropriate page
        exit;
    }

    if (($_GET['jb_action'] == "purchase_beyonic")) { // purchasing through beyonic instead of ewallet
        $packid = $_GET['packageid'];
        $pid = $_GET['hiddenpid'];

        if (!empty($packid)) {
            if ($packid == "base") {
                $total_job_price = get_post_meta($pid, 'price', true);
                $package = __('Base', 'pricerrtheme');

                $total_job_price_grand = $total_job_price;
                $order_type = "base";
                $package_number = $packid;
            } else {

                $total_job_price = get_post_meta($pid, 'package_price_' . $packid, true);
                $package = get_post_meta($pid, 'package_name_' . $packid, true);

                $total_job_price_grand = $total_job_price;
                $order_type = "package";
                $package_number = $packid;
            }


            $tempOrder = new pricerr_order();
            $extrasCost = $tempOrder->get_total_amounts_for_extras($pid);
            $arrayOfExtras = $tempOrder->get_extras_array_from_get();

        }

        $total_job_price_grand += $extrasCost;

        $tax = pricerr_return_fees_of_amount($total_job_price_grand);
        $total_job_price_grand2 = $total_job_price_grand + $tax;

        $pst = get_post($pid);

        $wpcurrentuser = wp_get_current_user();

        //-----------------------

        include 'lib/Beyonic.php'; // import beyonic php lib

        $token = $params = NULL;
        $api_key = get_option('PricerrTheme_beyonic_api_key');//api key set in admin tab for beyonic
        $collections_api = 'https://app.beyonic.com/api/collectionrequests'; // api that will receive the money

        //get form details<br>$amount = $_POST['amount'];
        $amount = number_format($total_job_price_grand2, 2);//format amount to 2 decimal places
        $desc = $pst->post_title;
        $type = 'MERCHANT';//$_POST['type']; //default value = MERCHANT
        $reference = rand(1, 99) . time();//unique order id of the transaction, generated by merchant
        $first_name = $wpcurrentuser->user_login; //[optional]
        $last_name = $wpcurrentuser->user_login; //[optional]
        $email = $wpcurrentuser->user_email;
        $phonenumber = ''; //ONE of email or phonenumber is required

        $callback_url = get_site_url() . "/?beyonic_response_pay_for_job=1"; //redirect url, the page that will handle the response from beyonic.
        ?>

        <!-- PUT HTML FOR PAGE THAT WILL CONFIRM USER PHONE NO AND EMAIL AND ALLOW THEM TO EDIT INCASE THEY WANT TO PAY THROUGH A DIFFERENT PHONE.NO-->
        <?php die();


    }


    if (($_GET['jb_action'] == "listing_beyonic")) {
        $pid = $_GET['pid'];

        $pricerrtheme_get_total_cost_of_posting = pricerrtheme_get_total_cost_of_posting($pid);

        $PricerrTheme_enable_local_tax_fee = get_option('PricerrTheme_enable_local_tax_fee');
        $PricerrTheme_percent_fee_vat_thing = get_option('PricerrTheme_percent_fee_vat_thing');
        $special_tax = 0;

        if ($PricerrTheme_enable_local_tax_fee == "yes" and $PricerrTheme_percent_fee_vat_thing > 0) {
            //means processing fee is added
            $special_tax = round(0.01 * $PricerrTheme_percent_fee_vat_thing * ($pricerrtheme_get_total_cost_of_posting), 2);
        }

        $amount = $pricerrtheme_get_total_cost_of_posting + $special_tax;
        $pst = get_post($pid);
        $wpcurrentuser = wp_get_current_user();

//-----------------------

        include 'lib/Beyonic.php'; // import beyonic php lib


        $token = $params = NULL;
        $api_key = get_option('PricerrTheme_beyonic_api_key');//api key set in admin tab for beyonic
        $collections_api = 'https://app.beyonic.com/api/collectionrequests'; // api that will receive the money

//get form details<br>$amount = $_POST['amount'];
        $amount = number_format($amount, 2);//format amount to 2 decimal places
        $desc = $pst->post_title;
        $type = 'MERCHANT';//$_POST['type']; //default value = MERCHANT
        $reference = rand(1, 99) . time();//unique order id of the transaction, generated by merchant
        $first_name = $wpcurrentuser->user_login; //[optional]
        $last_name = $wpcurrentuser->user_login; //[optional]
        $email = $wpcurrentuser->user_email;
        $phonenumber = ''; //ONE of email or phonenumber is required

        $callback_url = 'http://www.test.com/redirect.php'; //redirect url, the page that will handle the response from beyonic.

        ?>

        <!-- PUT HTML FOR PAGE THAT WILL CONFIRM USER PHONE NO AND EMAIL AND ALLOW THEM TO EDIT INCASE THEY WANT TO PAY THROUGH A DIFFERENT PHONE.NO-->
        <?php die();

    }
}


function pricerrtheme_hook_on_payment_service_beyonic($pid)
{
// uncomment this and add change the url parameter to a payment page(see beyonic pricerr_temp_redir function) --- disregarded it since all payment is through ewallet
    $en = get_option('PricerrTheme_beyonic_enable');
    if ($en == "yes") {
        $hiddenpid = $_GET['hiddenpid'];
        if (!empty($hiddenpid)) {

            $packid = $_GET['packageid'];
            if (!is_numeric($packid)) {
                $packid = "base";
            }
            ?>
            <button class="btn btn-primary green-button-me"
                    onclick="location.href='<?php echo get_site_url() ?>/?jb_action=purchase_beyonic&packageid=<?php echo $packid ?>&hiddenpid=<?php echo $hiddenpid ?>&tms=<?php echo current_time('timestamp', 0) ?><?php echo pricerr_get_extras_params() ?>'"><?php _e('Pay by Beyonic', 'pricerrtheme') ?></button>

            <?php
        } else {
            ?>
            <button class="btn btn-primary green-button-me"
                    onclick="location.href='<?php /*echo get_site_url() */ ?>/?jb_action=listing_beyonic&pid=<?php /*echo $pid */ ?>'"><?php /*_e('Pay by Beyonic', 'pricerrtheme') */ ?></button>

            <?php
        }
    }

}


function PricerrTheme_add_new_beyonic_pst()
{

    if (isset($_POST['PricerrTheme_save_beyonic'])):

        $PricerrTheme_beyonic_secret_key = trim($_POST['PricerrTheme_beyonic_secret_key']);
        $PricerrTheme_beyonic_consumer_key = trim($_POST['PricerrTheme_beyonic_consumer_key']);
        $PricerrTheme_beyonic_enable = $_POST['PricerrTheme_beyonic_enable'];

        update_option('PricerrTheme_beyonic_secret_key', $PricerrTheme_beyonic_secret_key);
        update_option('PricerrTheme_beyonic_consumer_key', $PricerrTheme_beyonic_consumer_key);
        update_option('PricerrTheme_beyonic_enable', $PricerrTheme_beyonic_enable);

    endif;
}


function PricerrTheme_add_new_beyonic_tab()
{
    ?>

    <li><a href="#tabs_beyonic">Beyonic</a></li>

    <?php

}


function PricerrTheme_add_new_beyonic_cnt()
{
    $arr = array("yes" => __("Yes", 'PricerrTheme'), "no" => __("No", 'PricerrTheme'));

    ?>

    <div id="tabs_beyonic">

        <form method="post"
              action="<?php bloginfo('siteurl'); ?>/wp-admin/admin.php?page=payment-methods&active_tab=tabs_beyonic">
            <table width="100%" class="sitemile-table">

                <tr>
                    <td valign=top width="22"><?php PricerrTheme_theme_bullet(); ?></td>
                    <td width="200"><?php _e('Enable:', 'PricerrTheme'); ?></td>
                    <td><?php echo PricerrTheme_get_option_drop_down($arr, 'PricerrTheme_beyonic_enable'); ?></td>
                </tr>


                <tr>
                    <td valign=top width="22"><?php PricerrTheme_theme_bullet(); ?></td>
                    <td><?php _e('Consumer Key:', 'PricerrTheme'); ?></td>
                    <td><input type="text" size="45" name="PricerrTheme_beyonic_consumer_key"
                               value="<?php echo get_option('PricerrTheme_beyonic_consumer_key'); ?>"/></td>
                </tr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3   r4       4              rfv                 rfv                         r

                <tr>
                    <td valign=top width="22"><?php PricerrTheme_theme_bullet(); ?></td>
                    <td><?php _e('Secret key:', 'PricerrTheme'); ?></td>
                    <td><input type="text" size="45" name="PricerrTheme_beyonic_secret_key"
                               value="<?php echo get_option('PricerrTheme_beyonic_secret_key'); ?>"/></td>
                </tr>


                <tr>
                    <td></td>
                    <td></td>
                    <td><input type="submit" name="PricerrTheme_save_beyonic"
                               value="<?php _e('Save Options', 'PricerrTheme'); ?>"/></td>
                </tr>

            </table>
        </form>

    </div>

    <?php

}


?>
